# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources in a bicep file in one environment
# This template is optimized for a Linux build agent -- see create-infra-win.yml for a Windows build agent
# ----------------------------------------------------------------------------------------------------
parameters:
- name: environmentName
  default: 'DEV'
- name: templateFolderName
  default: 'infra/Bicep'
- name: templateFileName
  default: 'main.bicep'
- name: serviceEndpointName
  default: ''
- name: resourceGroupName
  default: ''
- name: instanceName
  default: ''
- name: locationName
  default: 'eastus'
- name: workSpaceName
  default: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: ${{ parameters.environmentName }}

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
    - name: templateFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}'

  # ----------------------------------------------------------------------------------------------------
  steps:
  - bash: |
      echo "environmentName=${{ parameters.environmentName }}"
      echo "templateFolderName=${{ parameters.templateFolderName }}"
      echo "templateFileName=${{ parameters.templateFileName }}"
      echo "serviceEndpointName=${{ parameters.serviceEndpointName }}"
      echo "resourceGroupName=${{ parameters.resourceGroupName }}"
      echo "instanceName=${{ parameters.instanceName }}"

      echo "##[group]Display All Environment Variables:"
      printenv | sort
      echo "##[endgroup]"

      echo "----------------------------------------"
      echo "##[group]Directory of pipeline workspace:"
      tree -L 4 $(Pipeline.Workspace)
      echo "##[endgroup]"
    displayName: 'Display Variables and Files'
    continueOnError: true

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -appInsightsName ${{ parameters.instanceName }}
        -logAnalyticsWorkspaceName ${{ parameters.workSpaceName }}
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: ${{ parameters.serviceEndpointName }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resourceGroupName }}
      location: ${{ parameters.locationName }}
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental' # 'Incremental' | 'Complete' | 'Validation'
